### ISSUE TITLE
null check operator used on a null value

### ISSUE THREAD

**Issue by bashtoc** [ernestkoko/monnify_flutter#1] opened 2022-07-25 05:08 UTC
hello chief, i tried running the monnify flutter plugin with flutter 3.0 and the plugin kept returning null check operator used on a null value anytime makepayment is called. is there something i'm missing sir?

**Comment by ernestkoko** [comment] 2022-07-25 12:36
Okay @bashtoc, please can I have your code sample that is throwing the error?

**Comment by bashtoc** [comment] 2022-07-26 11:27
class Monnify extends StatefulWidget {
  const Monnify({Key? key}) : super(key: key);




  @override
  State<Monnify> createState() => _MonnifyState();
}

class _MonnifyState extends State<Monnify> {
  final _monnifyPlugPlugin = MonnifyFlutter.instance;
  final TextEditingController nameController = TextEditingController();
  final TextEditingController emailController = TextEditingController();
  final TextEditingController amountController = TextEditingController();

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    // We also handle the message potentially returning null.monnify.
    try {
      final result = await _monnifyPlugPlugin.initializeMonnify(

        ///Enter your API key here from monnify
          apiKey: 'MK_TEST_7AUEY6NEE8',

          ///Enter your contract code here from monnify
          contractCode: '9030446776',
          applicationMode: ApplicationMode.test);

      print("Initialisation Result:  $result");
    } on Exception {
      print('Failed to get platform version.');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Monnify Plugin'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Center(
            child: ListView(
              children: [
                const SizedBox(
                  height: 10.0,
                ),
                customTextField(hint: "Name:", controller: nameController),
                const SizedBox(
                  height: 10.0,
                ),
                customTextField(hint: "Email:", controller: emailController),
                const SizedBox(
                  height: 10.0,
                ),
                customTextField(hint: "Amount:", controller: amountController),
                const SizedBox(
                  height: 10.0,
                ),
                TextButton(
                  style: TextButton.styleFrom(
                      backgroundColor: Theme.of(context).primaryColor,
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10))),
                  onPressed: () async {
                    try {
                      final result = await _monnifyPlugPlugin.makePayment(
                          amount: amountController.text,
                          currencyCode: "NGN",
                          customerName: nameController.text,
                          customerEmail: emailController.text,
                          paymentReference: referenceId(),
                          paymentDescription: "Testinggg",
                          paymentMethod: PaymentMethod.all);
                    } catch (error) {
                      print("Errror: $error");
                    }
                  },
                  child: const Text(
                    "Pay",
                    style: TextStyle(color: Colors.white, fontSize: 30),
                  ),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }

  ///Randomly generated string
  String referenceId() => DateTime.now().toString();

  ///Custom text field
  Widget customTextField(
      {String? hint,
        TextEditingController? controller,
        FocusNode? focusNode,
        String? errorText,
        Widget? suffixIcon,
        bool readOnly = false,
        TextInputType? textInputType,
        ValueChanged<String>? onChanged,
        Widget? label}) {
    return TextField(
        controller: controller,
        focusNode: focusNode,
        readOnly: readOnly,
        decoration: InputDecoration(
          suffixIcon: suffixIcon,
          errorText: errorText,
          hintText: hint,
          label: label,
          enabledBorder: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.blue, width: 2),
            borderRadius: BorderRadius.all(
              Radius.circular(10),
            ),
          ),
          labelStyle: const TextStyle(fontWeight: FontWeight.bold),
          border: const OutlineInputBorder(
            borderSide: BorderSide(color: Colors.blue, width: 10),
            borderRadius: BorderRadius.all(
              Radius.circular(10),
            ),
          ),
        ),
        onChanged: onChanged,

        // onChanged: controller.onMeterNumberChanged,
        keyboardType: textInputType,
        textInputAction: TextInputAction.next,
        onEditingComplete: () => {});
  }
}

**Comment by bashtoc** [comment] 2022-07-26 11:28
hello sir, please have a look at the code sample, if you can point me out to another that works, i will appreciate. thank you.

**Comment by ernestkoko** [comment] 2022-07-26 20:58
Okay. I have run your code sample and the issue is you are not setting the phone number parameter when making payment:

```
final result = await _monnifyPlugPlugin.makePayment(
                          amount: amountController.text,
                          currencyCode: "NGN",
                          customerName: nameController.text,
                          customerEmail: emailController.text,
                          paymentReference: referenceId(),
                          paymentDescription: "Testinggg",
                          customerPhoneNumber: "08123434590",
                          paymentMethod: PaymentMethod.all);

```

Try this.it will work and if you encounter any other error let me know.

I will make the phone number a required parameter to the function on next release.

**Comment by ernestkoko** [comment] 2022-07-27 09:04
Please confirm it is working so I can close this issue

**Comment by bashtoc** [comment] 2022-07-27 12:05
yea bro, its working, thanks for your swift response. 👍😍❤️

**Comment by bashtoc** [comment] 2022-07-27 12:06
please WHATS YOUR TWITTER OR IG handle?

**Comment by ernestkoko** [comment] 2022-07-27 12:21
Thanks!
[My twitter handle is](https://www.twitter.com/ernest_eferetin)  ernest_eferetin

So I am closing this issue.

**Closed as completed** 2022-07-27 12:23 UTC
